### ISSUE TITLE
About Peskas text for portal

### ISSUE THREAD

**Issue by altilley** [WorldFishCenter/peskas.timor.portal#6]

**Comment by altilley** [comment]
These are the links for the papers I mention at the end of the "About Peskas" text for the portal
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0234760
http://www.fao.org/documents/card/en/c/cb2030en
https://www.frontiersin.org/articles/10.3389/fmars.2019.00487/full

**Comment by efcaguab** [comment]
Closed in #8
